version: 2.1
jobs:
  build:
    docker:
      - image: circleci/python:3.8

    working_directory: ~/myapp

    steps:
      - checkout

      # Install Node.js and npm
      - run:
          name: Install Node.js and npm
          command: |
            curl -sL https://deb.nodesource.com/setup_14.x | sudo -E bash -
            sudo apt-get install -y nodejs

      # Install Python dependencies and run tests
      - run:
          name: Install Python dependencies and run tests
          command: |
            python -m venv venv
            source venv/bin/activate
            pip install -r backend/requirements.txt
            pytest backend/tests

      # Build the React app
      - run:
          name: Build React app
          command: |
            cd frontend
            npm install
            npm run build

  deploy:
    docker:
      - image: circleci/python:3.8

    working_directory: ~/myapp

    steps:
      - checkout

      # Deploy your application here (e.g., push to your server)

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
